// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwu81MVCPTNzWfzS1A51BcdioefMaOpI',
    appId: '1:166842085019:web:459ba6725e6c558473603e',
    messagingSenderId: '166842085019',
    projectId: 'carrentalco-cfdc8',
    authDomain: 'carrentalco-cfdc8.firebaseapp.com',
    storageBucket: 'carrentalco-cfdc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb78Y4EUMUg9JVKsdnuJVhJnW3Y8Jv2JY',
    appId: '1:166842085019:android:52354344e491812b73603e',
    messagingSenderId: '166842085019',
    projectId: 'carrentalco-cfdc8',
    storageBucket: 'carrentalco-cfdc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPh7qfHU-cJyAIi0wlFbxzjvPaRbOVmM',
    appId: '1:166842085019:ios:a956c7937793d49f73603e',
    messagingSenderId: '166842085019',
    projectId: 'carrentalco-cfdc8',
    storageBucket: 'carrentalco-cfdc8.appspot.com',
    iosClientId: '166842085019-lemfn2m3sdvop5hvnkivmut25aip6em7.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrentalco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPh7qfHU-cJyAIi0wlFbxzjvPaRbOVmM',
    appId: '1:166842085019:ios:a1106b5890ecbd7d73603e',
    messagingSenderId: '166842085019',
    projectId: 'carrentalco-cfdc8',
    storageBucket: 'carrentalco-cfdc8.appspot.com',
    iosClientId: '166842085019-trhrhg286j084c6jggiv9utrir91sqbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrentalco.RunnerTests',
  );
}
